language: c
before_install:
- sudo apt-get install binutils-mingw-w64-i686 gcc-mingw-w64-i686
- wget http://ftp.gnome.org/pub/gnome/binaries/win32/gtk+/2.14/gtk+-bundle_2.14.7-20090119_win32.zip
  -O gtk.zip
- unzip gtk.zip -d gtk
- curl http://freefr.dl.sourceforge.net/project/pidgin/Pidgin/2.10.12/pidgin-2.10.12.tar.bz2
  | tar xj
- wget http://aebrahim.github.io/pidgin-wincred/lib.zip
- unzip lib.zip
- rm gtk.zip lib.zip
script: make
before_deploy: zip pidgin-wincred_${TRAVIS_TAG}.zip pidgin-wincred.dll
deploy:
  provider: releases
  api_key:
    secure: gGoos91hSV0QmvpnnOTcUhSDJQWVe/LLTXXNTlVaPztzNbayzgUbwTZ9wERKLnymRyvWEaC1kGCqM9qN6YvlD91z8F0NuCiuGhdWMYVPf5LpXQRgSo+PqZXLXYJLqrw+wwH96wuevoeIv9W5RxpfF2USif3S7JBUtcPy8fUoBus=
  file: pidgin-wincred_${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    repo: aebrahim/pidgin-wincred
    all_branches: true
    tags: true
